[package]
name = "nickmass-com"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
serde = "1.0.89"
serde_derive = "1.0.89"
warp = "0.1.14"
redis = "0.10.0"
serde_json = "1.0.39"
url = "1.7.2"
reqwest = "0.9.12"
jwt = "0.4.0"
base64 = "0.10.1"
ring = "0.14.6"
env_logger = "0.6.1"
log = "0.4.6"
askama = "0.8.0"
pulldown-cmark = "0.4.0"
chrono = "0.4.6"
structopt = "0.2.15"
toml = "0.5.0"
