[package]
name = "nickmass-com"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]
edition = "2018"

[dependencies]
futures= "0.3.1"
serde = { version = "1.0", features = ["derive"] }
warp = "0.2.1"
redis = { version = "0.15.1", features = ["tokio-rt-core"] }
serde_json = "1.0"
url = "2.1"
reqwest = { version = "0.10.1", features = ["json"] }
jwt = "0.4.0"
base64 = "0.11.0"
ring = "0.14.6"
env_logger = "0.7.1"
log = "0.4.8"
askama = "0.9.0"
pulldown-cmark = "0.6.1"
chrono = "0.4.10"
structopt = "0.3.8"
tokio = { version = "0.2.10", features = ["full"] }
toml = "0.5.6"
