[config]
skip_core_tasks = true

[tasks.install-wasm-pack]
script_runner = "@shell"
script = [
'''
wasm-pack -V || cargo install wasm-pack
'''
]

[tasks.build-client]
command = "wasm-pack"
args = ["build", "--release", "--out-dir", "../dist/public/js", "--target", "web", "--no-typescript", "./client"]
dependencies = ["install-wasm-pack"]

[tasks.build-server]
command = "cargo"
args = ["build", "--release"]

[tasks.css]
script_runner = "@shell"
script = [
'''
cat ./public/css/normalize.css ./public/css/skeleton.css ./public/css/site.css > ./dist/public/css/bundle.css
'''
]

[tasks.clean]
script_runner = "@shell"
script = [
'''
rm -rf ./dist
mkdir -p ./dist/public
mkdir -p ./dist/public/css
mkdir -p ./dist/public/js
'''
]

[tasks.default]
script_runner = "@shell"
script = [
'''
cp ./target/release/nickmass-com ./dist
cp -r ./public ./dist
'''
]
dependencies = ["clean", "build-client", "build-server", "css"]

